<?php
function uitoux_accordion_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'uitoux_accordion'),
  );
}

function template_preprocess_views_uitoux_accordion_view(&$variables) {
  /*$options['views_horizontal_slider'] = $variables['options'];
  $path = drupal_get_path('module', 'views_horizontal_slider');

  drupal_add_js($path . '/slider.js');
  drupal_add_js($options, 'setting');
  drupal_add_css($path . '/views_horizontal_slider.css');*/
}