<?php
function uitoux_accordion_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'uitoux_accordion'),
  );
}

function template_preprocess_views_uitoux_accordion_view(&$variables) {
  $options = array('views_uitoux_accordion' => $variables['options']);
  $path = drupal_get_path('module', 'uitoux_accordion');

  $lib = libraries_detect('easing');
  if($lib['installed']) {
  	foreach($lib['files'] as $type => $files) {
  		if($type == 'js') {
	  		foreach($files as $js_file => $det) {
	  			drupal_add_js($lib['library path'].'/'.$js_file);
	  		}
  		}
  	}
  }

  drupal_add_js($path . '/js/zozo.accordion.min.js');
  drupal_add_js($options, 'setting');
  drupal_add_css($path . '/css/zozo.accordion.min.css');
  drupal_add_css($path . '/css/zozo.styles.min.css');
}